In [ ]:
import torch 
a = torch.rand((50, 10))
b = torch.rand((100, 10))

c = torch.einsum("ij,nj->in", a , b)

(c.view(-1, 1).mm(a.view(1, -1))).shape
c.view(-1, 1).shape
for i in (a):
    print(1)

In [127]:
a = torch.rand((5, 5)) - torch.rand((5, 5))
c = a.apply_(lambda x: max(0, x))
print(c)
z = (c != torch.tensor([0])) 
torch.tensor([0]) + z

tensor([[0.0080, 0.0000, 0.6692, 0.4163, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2300, 0.5042, 0.5466],
        [0.0000, 0.2070, 0.0000, 0.3685, 0.0575]])


tensor([[1, 0, 1, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1],
        [0, 1, 0, 1, 1]])

In [140]:
class Module:
    # Defining __call__ method to keep the easy syntax for the forward prop
    def __call__(self, input):
        return self.forward(input)
    
    def forward(self, input):
        raise NotImplementedError
    
    def backward(self, gradwrtoutput):
        raise NotImplementedError
    
    def params(self):
        raise NotImplementedError

class ReLU(Module):
    
    def forward(self, input):
        return input.apply_(lambda x: max(0, x))

    def derivative(self,input):
        der_bool = (self.forward(input) != torch.tensor([0])) # True if ReLU of x is not zero
        return der_bool #+ torch.tensor([0]) # only to give back non-boolean tensor explicitly

In [142]:
relu = ReLU()

print(relu(a))
relu.derivative(a)

tensor([[0.0080, 0.0000, 0.6692, 0.4163, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2300, 0.5042, 0.5466],
        [0.0000, 0.2070, 0.0000, 0.3685, 0.0575]])


tensor([[ True, False,  True,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True,  True,  True],
        [False,  True, False,  True,  True]])